version: "3.7"
services: 
  test-server:
    container_name: test-server
    build: https://github.com/nsa5953/ansible-docker.git
    image: centos8-systemd
    privileged: true
    restart: always
    ports:
      - "5001:22"
      - "5080:80"
      - "443:443"
    networks: 
      - ansible-test-network
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro 

  test-node1:
    container_name: test-node1
    image: centos8-systemd:latest
    privileged: true
    restart: always
    ports: 
      - "5002:22"
    networks:
      - ansible-test-network
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  test-node2:
    container_name: test-node2
    image: centos8-systemd:latest
    privileged: true
    restart: always
    ports:
      - "5003:22"
    networks:
      - ansible-test-network
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  ubuntu-node:
    container_name: ubuntu-node
    image: ubuntu:latest
    tty: true
    privileged: true
    restart: always
    ports: 
      - "5004:22"
    networks:
      - ansible-test-network
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

networks:
  ansible-test-network: {}


